FROM fedora:%%OS_VERSION%%

LABEL maintainer="Nektar++ Development Team <nektar-users@imperial.ac.uk>"

ENV FEDORA_VERSION %%OS_VERSION%%
COPY docker/nektar-env/fedora${FEDORA_VERSION}_default_packages.txt packages.txt

RUN	yum install -y $(cat packages.txt) \
	&& yum clean all

# Enable use of ccache
RUN ln -s /usr/bin/ccache /usr/local/bin/cc && ln -s /usr/bin/ccache /usr/local/bin/c++ 

RUN groupadd nektar && useradd -m -g nektar nektar
USER nektar:nektar
RUN mkdir /home/nektar/nektar
WORKDIR /home/nektar/nektar
