FROM %%BASE_IMAGE%%:env-debian-bullseye-default

USER root
COPY docker/nektar-env/bullseye_documentation_packages.txt packages.txt

RUN echo "deb http://deb.debian.org/debian bullseye non-free" > \
        /etc/apt/sources.list.d/debian-non-free.list && \
        apt-get update && \
        apt-get install -y $(cat packages.txt) \
        && rm -rf /var/lib/apt/lists/*

# Patch security policy to allow PDF, EPS and PS conversion by ImageMagick
RUN sed -i 's/rights="none" pattern="\(PDF\|PS\|EPS\)"/rights="read|write" pattern="\1"/g' /etc/ImageMagick-6/policy.xml

USER nektar:nektar
