FROM fedora:32

# Install some basic build requirements.
RUN dnf install -y rpm-build dnf-plugins-core git

WORKDIR /root
COPY pkg/redhat/nektar-fedora-32.spec .

# Install build requirements from spec file.
RUN dnf builddep -y nektar-fedora-32.spec && rm -f nektar-fedora-32.spec
