FROM fedora:31

# Install some basic build requirements.
RUN dnf install -y rpm-build dnf-plugins-core git

WORKDIR /root
COPY redhat/nektar-fedora.spec .

# Install build requirements from spec file.
RUN dnf builddep -y nektar-fedora.spec && rm -f nektar-fedora.spec
